Feature/add cache
gregurco/GuzzleBundleOAuth2Plugin pull request #16
Opened 2018-12-19 12:31 UTC by chrisivens

Allow the `persistent` option to store the tokens in cache if the grant type is client credentials. This will use the standard PSR-6 interface that Symfony works with and is configured as `cache.app`.

The code in `src/GuzzleBundleOAuth2Plugin.php` which chooses the class to return for the persistence middleware could probably be refactored at some point but does work in our tests against a redis cache storage.

2018-12-19 23:28 UTC, gregurco requested changes

2018-12-19 23:28 UTC, gregurco commented on composer.json
> +    "repositories": [
please remove modifications in composer.json

2018-12-19 23:28 UTC, gregurco commented on src/Middleware/CachedOAuthMiddleware.php
> +        ?GrantTypeInterface $grantType = null,
plugin supports PHP 7.0, but definition `?type` was introduces in PHP 7.1. Could you check compatibility with 7.0?

2018-12-19 23:28 UTC, gregurco commented on src/GuzzleBundleOAuth2Plugin.php
> +                            new Reference('Symfony\Component\Cache\Adapter\AdapterInterface'),
could you write here `new Reference(AdapterInterface::class),` ?

2018-12-20 09:12 UTC, chrisivens commented on composer.json
> +    "repositories": [
Sorry about this section, I missed it when prepping the PR.

2018-12-20 09:12 UTC, chrisivens commented on src/Middleware/CachedOAuthMiddleware.php
> +        ?GrantTypeInterface $grantType = null,
Done

2018-12-20 09:13 UTC, chrisivens commented on src/GuzzleBundleOAuth2Plugin.php
> +                            new Reference('Symfony\Component\Cache\Adapter\AdapterInterface'),
Not quite sure why I did it the other way, I don't normally use a string literal. Change made.

2018-12-20 09:16 UTC, chrisivens commented
Not sure why my commits were not being picked up as I pushed them so I ended up having to force push to get them through.

2018-12-20 09:25 UTC, gregurco commented
@chrisivens could you please squash commits to have just one instead of 8? Do you know how to do that?

2018-12-20 10:08 UTC, chrisivens commented
Yep, I'll do that.

2018-12-20 11:55 UTC, merged

2018-12-20 11:56 UTC, gregurco commented
@chrisivens thank you! Merged :+1:

2019-01-07 11:13 UTC, chrisivens commented
Any change of a tagged release for this?

2019-01-07 16:01 UTC, gregurco commented
@chrisivens thank you for reminder :slightly_smiling_face: 
Released: https://github.com/gregurco/GuzzleBundleOAuth2Plugin/releases/tag/v1.0.6